### ISSUE TITLE
modulus operation in the back-propagation

### ISSUE THREAD

**Issue by boyu-zhang-25** [sgoldt/nn2pp#1]
Hi, 

In line 578 of `libnn2pp.h`, for dwdx, why do we take the modulus?

Specifically, `deriv.each_col() %= v;`, where `deriv` is the derivative w.r.t. the ERF activation. Normally, one should be multiplying `v` to dwdx. 

Thank you!

**Comment by boyu-zhang-25** [comment]
Sorry, it is the Armadillo multiplication operation. My bad.

**Comment by sgoldt** [comment]
Exactly, the % operator is overloaded in Armadillo to provide element-wise multiplication:
http://arma.sourceforge.net/docs.html#operators
